добавила стили
htmlacademy-htmlcss/2114175-sedona-34 pull request #6
Opened 2022-06-24 21:32 UTC by Rodika94

2022-06-24 22:30 UTC, Rodika94 commented
ну че такое с этим пулреквестом вообще

2022-06-25 10:20 UTC, Dima-Dim requested changes

2022-06-25 10:20 UTC, Dima-Dim commented on index.html
> +            <div class="divider-container">
Аж 3 тега, да ещё и с текстом ради декоративного элемента? :))) Нет. Всего этого в разметке быть не должно. Как будто раздел про декоративные элементы прошёл мимо.

2022-06-25 10:20 UTC, Dima-Dim commented on index.html
> +              <div class="home"></div>
Этот и подобные пустые теги https://up.htmlacademy.ru/htmlcss/34/criteries#HTML-06

2022-06-25 10:20 UTC, Dima-Dim commented on styles/styles.css
> +.twelve {
Там же не всегда будет 12.

2022-06-26 03:13 UTC, Dima-Dim requested changes

2022-06-26 03:13 UTC, Dima-Dim commented on index.html
> +            <div class="divider">
Ещё раз. не должно всего этого быть в разметке.

2022-06-26 03:13 UTC, Dima-Dim commented on index.html
> +              <div class="home">
Для чего этот лишний контейнер?

2022-06-27 02:05 UTC, merged